Fix profile update bug
marcua/ayb pull request #268
Opened 2024-01-09 04:23 UTC by marcua

Resolves #265 (I think---had to run `cargo clean` and waiting a while now :))

2024-01-09 06:23 UTC, sofiaritz requested changes
Exactly what I had in mind :)
Could you add a test case in the E2E tests to catch this bug in the future if there's some regression?

2024-01-10 00:30 UTC, marcua commented on tests/e2e.rs
> +    update_profile(
Fails on `main`, succeeds in this branch

2024-01-10 00:31 UTC, marcua commented
Great idea, added! :)

2024-01-10 03:07 UTC, marcua commented
I'll merge this, but if you spot any other issues, I'm happy to iterate in another PR! :)

2024-01-10 03:07 UTC, merged